[versions]
androidGradlePlugin = "7.4.0"
kotlinAndroid = "1.7.0"
androidxCore = "1.7.0"
androidxActivity = "1.3.1"
androidxLifecycle = "2.3.1"
androidxComposeUi = "1.2.0"
junit = "4.13.2"
androidxJunit = "1.1.3"
espressoCore = "3.4.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity"}
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle"}
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxComposeUi" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidxComposeUi" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeUi" }
composeUiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxComposeUi" }
junit = { module = "junit:junit", version.ref = "junit" }
androidJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit"}
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinAndroid"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid"}
