[versions]
androidGradlePlugin = "7.4.0"
kotlinAndroid = "1.7.0"
kotlinKapt = "1.7.10"
androidxCore = "1.7.0"
androidxActivity = "1.3.1"
androidxLifecycle = "2.3.1"
androidxComposeUi = "1.3.1"
androidxViewModelCompose = "2.5.1"
compose-compiler = "1.3.1"
junit = "4.13.2"
androidxJunit = "1.1.3"
espressoCore = "3.4.0"
navVersion = "2.5.3"
hilt = "2.44.2"
hiltNavigationCompose = "1.0.0"
composeRuntimeLiveData = "1.3.3"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity"}
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle"}
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxComposeUi" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidxComposeUi" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxViewModelCompose"}
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeUi" }
composeUiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxComposeUi" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "composeRuntimeLiveData" }
junit = { module = "junit:junit", version.ref = "junit" }
androidJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit"}
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinAndroid"}
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinKapt"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
