name: Pull Request

on:
  pull_request:

jobs:
  build_job:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout the code
       uses: actions/checkout@v3
   
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
       
     - name: Build the app
        run: ./gradlew clean assembleDebug

    - name: Run Unit tests
        run: ./gradlew test
