name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Bundle Release and Apk
        run: ./gradlew bundleRelease -x test

      - name: Sign Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEYBASE_64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/bundle/release/app-release.aab

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create service_account.json
        id: createServiceAccount
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo $SERVICE_ACCOUNT_JSON > service_account.json

      - name: Downloading build
        uses: actions/download-artifact@v2
        with:
          name: bundle

      - name: Deploy to Play Store Internal
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.sidgowda.pawcalc
          track: internal
          releaseFiles: app-release.aab
          mappingFiles: app/build/outputs/mapping/release/mapping.txt

