name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Bundle Release and Apk
        run: ./gradlew bundleRelease assembleRelease

      - name: Sign Bundle
        id: signBundle
        uses: r0adkll/sign-android-release@v1.0.1
          with:
            releaseDirectory: app/build/outputs/bundle/release
            signingKeyBase64: ${{ secrets.SIGNING_PAWCALC_KEYSTORE_BASE_64 }}
            alias: ${{ secrets.SIGNING_KEY_ALIAS }}
            keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
            keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}

      - name: Sign Apk
        id: signApk
        uses: r0adkll/sign-android-release@v1.0.1
          with:
            releaseDirectory: app/build/outputs/apk/release
            signingKeyBase64: ${{ secrets.SIGNING_PAWCALC_KEYSTORE_BASE_64 }}
            alias: ${{ secrets.SIGNING_KEY_ALIAS }}
            keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
            keyPassword: ${{ secrets.SIGNING_ALIAS_PASSWORD }}

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/release
            app/build/outputs/bundle/release/

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        run: echo ${{ secrets.SERVICE_ACCOUNT_JSON }} > service_account.json

      - name: Deploy to Play Store Internal
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: service_account.json
          packageName: com.sidgowda.pawcalc
          track: internal
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFiles: app/build/outputs/mapping/release/mapping.txt

